title: Happy Cloud
author: Caroline
email: username@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about mindfulness and tech

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  caroline-reed # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
